pipeline {
	agent {
		label 'npm'
	}
	stages {
		stage('Index workspace') {
			steps {
				script {
					unityPackage {
						// define unity package location relative to repository
						PACKAGE_LOCATION = ''

						// which Unity Test Runner modes to execute
						TEST_MODES = 'EditMode PlayMode'

						// verify that code is formatted
						TEST_FORMATTING = '1'
						EDITORCONFIG_LOCATION = '.jenkins/.editorconfig'

						// which platforms to deploy to
						DEPLOY_TO_VERDACCIO = '0'
					}
				}
			}
		}
	}
}