pipeline {
	agent {
		label 'npm && linux'
	}
	environment {
		BRANCH_NAME = 'main'
	}
	stages {
		stage('Index workspace') {
			steps {
				script {
					def nodes = []
					Jenkins.instance.getNodes().each { node ->
						if (node.getComputer().isOnline()) {
							def label = node.getLabelString()
							if (label.contains('unity') && label.contains('linux')) {
								def name = node.getNodeName()
								echo "Identified Unity node '${name}'"
								nodes.add(name)
							}
						}
					}

					for (def name : nodes.sort()) {
						stage("Node: ${name}") {
							unityPackage {
								// define unity package location relative to repository
								PACKAGE_LOCATION = ''
								UNITY_NODE = name

								// which Unity Test Runner modes to execute
								TEST_MODES = 'EditMode PlayMode'

								// verify that code is formatted
								TEST_FORMATTING = '1'
								EDITORCONFIG_LOCATION = '.jenkins/.editorconfig'

								// which platforms to deploy to
								DEPLOY_TO_VERDACCIO = '0'
							}
						}
					}
				}
			}
		}
	}
}