name: Create Documentation

on:
  push:
    branches:
      - main

jobs:
  create-documentation:
    name: Create Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: false
      - name: DocFX
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: ./.docfx/docfx.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docfx/docs